hwt: refactor IOC_BUFPTR_GET
CTSRD-CHERI/freebsd-morello pull request #10
Opened 2024-05-31 09:19 UTC by zdleaf

Make this a bit less backend specific by renaming curpage - SPE is not working with pages

Plus we need an extra `*data` field to pass various flags

2024-06-26 14:08 UTC, bukinr commented on sys/arm64/arm64/locore.S
> +	orr	x2, x2, (3 << 12)
is this bit available on all arm64 machines? (or should we enable SPE at EL1 by request?)
also we need to unmagic the bits

2024-06-26 15:18 UTC, zxombie commented on sys/arm64/arm64/locore.S
> +	orr	x2, x2, (3 << 12)
This should be safe as on earlier revisions of the Architecture those bits did nothing.

2024-06-26 15:21 UTC, zxombie commented on sys/dev/hwt/hwt_hook.c
> +				WRITE_SPECIALREG(CONTEXTIDR_EL1_REG, p->p_pid);
We should update `contextidr_el1` in the thread switcher. I didn't do it previously as I was unsure what the register was for.

2024-07-01 10:46 UTC, zdleaf commented on sys/dev/hwt/hwt_hook.c
> +				WRITE_SPECIALREG(CONTEXTIDR_EL1_REG, p->p_pid);
Okay. Maybe we should introduce some kind of additional config option to enable/disable this, although I don't know if it's useful outside of hardware tracing. We can enable/disable it otherwise based on if HWT_HOOKS since it adds additional instructions to context switching.

2024-07-01 14:53 UTC, zxombie commented on sys/dev/hwt/hwt_hook.c
> +				WRITE_SPECIALREG(CONTEXTIDR_EL1_REG, p->p_pid);
There is also a use by the debug logic, e.g. breakpoints & watchpoints, although I'm not sure how useful it is there.

2024-07-01 16:49 UTC, zdleaf commented on sys/dev/hwt/hwt_hook.c
> +				WRITE_SPECIALREG(CONTEXTIDR_EL1_REG, p->p_pid);
I will add a separate conf option to toggle it then.

2024-07-05 15:04 UTC, zdleaf commented on sys/dev/hwt/hwt_hook.c
> +				WRITE_SPECIALREG(CONTEXTIDR_EL1_REG, p->p_pid);
I've added a kernel conf option + sysctl switch for that. See [arm64: write PID in CONTEXTIDR_EL1 on ctx switch](https://github.com/CTSRD-CHERI/freebsd-morello/pull/10/commits/1fffa1f5c4c56963e526401a30257768e01e879e). I'll send this for a separate review on Phab.

2024-07-05 15:05 UTC, zdleaf commented on sys/arm64/arm64/locore.S
> +	orr	x2, x2, (3 << 12)
Fixed. This value will need to change once Andy's VHE patches are in or close to in.

2024-07-05 15:21 UTC, zdleaf commented on sys/arm64/arm64/sys_machdep.c
> +SYSCTL_BOOL(_machdep, OID_AUTO, pid_in_contextidr, CTLFLAG_RW,
I'm not sure machdep is the correct place for this. The debug sysctl was another place I considered.

2024-07-30 09:00 UTC, bukinr requested changes
looks good!

2024-07-30 09:00 UTC, bukinr commented on sys/dev/hwt/hwt_hook.c
> +	error = hwt_thread_alloc(&thr, path, ctx);
per discussion in IRC, could we restore this line? dereferencing ctx may not work as we released ref a line before

2024-08-06 10:26 UTC, zdleaf commented on sys/dev/hwt/hwt_hook.c
> +	error = hwt_thread_alloc(&thr, path, ctx);
Done

2024-08-06 10:32 UTC, zdleaf commented
- Rebase
- Removed kernel conf option for CONTEXTIDR_EL1
- Sent `arm64:` patches upstream:
    - https://reviews.freebsd.org/D46191
    - https://reviews.freebsd.org/D46192
- Fixed kva_req/bufsize arg

2024-08-06 10:47 UTC, zdleaf commented
- Fix comment in [hwt: spe: unmagic MDCR bits](https://github.com/CTSRD-CHERI/freebsd-morello/pull/10/commits/cec0b86f61cbc0c735d63920b3809e959e083d87)

2024-08-06 14:10 UTC, merged